### ISSUE TITLE
Unbale to match /dev/sd[a-z][a-z]* with -g

### ISSUE THREAD

**Issue by samuraiii** [Napsty/check_smart#21]
Hello,
I am unable to match all devices on big disk node which has devices from /dev/sda to /dev/sdcc...
When I use "/dev/sd[a-z]" I get only /dev/sda to /dev/sdz, when I use "/dev/sd[a-z][^0-9]"  I get /dev/sda1 to /dev/sdz9, only partitions. With "/dev/sd[a-z][a-z]" I get /dev/sdaa to /dev/sdcc including partitons.
Any try with counts "{1,2}" or "+" results in "Could not find any valid block/character special device for pattern"
S

**Comment by hawson** [comment]
This is because the documentation is misleading:  it actually wants a glob, not a regex:

```
 97         if ( $opt_d ){
 98             # normal mode - push opt_d on the list of devices
 99             push(@dev,$opt_d);
100         } else {
101             # glob all devices - try '?' first 
102             @dev =glob($opt_g);
103         }
```

In your case, you could use  `-g "/dev/sd*[a-z]"` to get all of the raw devices.  The `*` will expand to zero or more letters, and the `[a-z]` forces a match at the end of the string.
