### ISSUE TITLE
Define default "raw attribute" check list

### ISSUE THREAD

**Issue by Napsty** [Napsty/check_smart#36]
Sometimes vendors use different attribute names. To catch as many as possible, this issue serves as placeholder/discussion to collect data. Help is much wanted and needed!
I will update the issue with relevant info from the comments below.

Note: This list does not apply to NVMe devices, as they use a different kind of attribute list.

## Current Default List
As of version 6.0, the current defined default list is:
`'Current_Pending_Sector,Reallocated_Sector_Ct,Program_Fail_Cnt_Total,Uncorrectable_Error_Cnt,Offline_Uncorrectable,Runtime_Bad_Block';`

### Current_Pending_Sector
- Attribute ID: 197
- Hard drives: :heavy_check_mark:
- Solid state drives: :x:
- Vendor alias: Seem to use the same name

### Reallocated_Sector_Ct
- Attribute ID: 5
- Hard drives: :heavy_check_mark:
- Solid state drives: :heavy_check_mark:
- Vendor alias: Seem to use the same name

### Program_Fail_Cnt_Total
- Attribute ID: 181
- Hard drives: :x:
- Solid state drives: :heavy_check_mark:
- Vendor alias: TBD

### Reported_Uncorrectable_Errors
- Attribute ID: 187
- Hard drives: :heavy_check_mark:
- Solid state drives: :heavy_check_mark:
- Vendor alias: Reported_Uncorrect (seen in SSD's and Seagate HDD)

### Uncorrectable_Error_Cnt
- Attribute ID: 198
- Hard drives: :heavy_check_mark:
- Solid state drives: :heavy_check_mark:
- Vendor alias: Offline_Uncorrectable (seen in Toshiba and WDC HDD, WDC SSD)

## Suggested changes

- Add `Reported_Uncorrect` and `Reallocated_Event_Count` to the default list

**Comment by deric** [comment]
Maybe add `Reallocated_Event_Count`? Seems to be [used by many vendors](https://kb.acronis.com/content/9132).
```
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       201
```
