### ISSUE TITLE
-g parameter is limited to 26 devices

### ISSUE THREAD

**Issue by casparsmit** [Napsty/check_smart#5]
The -g parameter only matches 26 devices when for instance you issue:

-g /dev/sd

It matches /dev/sda, /dev/sdb, ..... till /dev/sdz

BUT in a system with more disks (/dev/sdaa, sdab, sdac, etc.... ) these disks are ignored because the glob function does not match them:

line 78:

 @dev =glob($opt_g."?");

The ? matches only 1 character (a till z) so sdaa is ignored (and /dev/sda1 which is ok!)

So it should match /dev/sd [a-z][a-z] or something similar (Don't know how to convert that to perl)
to match /dev/sdaa too but not the numbered partitions like /dev/sda1.

**Comment by cguadall** [comment]
One line change --> @dev =glob($opt_g."*[a-z]");

Output:

./check_smart2.pl -g /dev/sd -i scsi
OK: [/dev/sda] - Device is clean --- [/dev/sdaa] - Device is clean --- [/dev/sdab] - Device is clean --- [/dev/sdac] - Device is clean --- [/dev/sdad] - Device is clean --- [/dev/sdae] - Device is clean --- [/dev/sdaf] - Device is clean --- [/dev/sdag] - Device is clean --- [/dev/sdah] - Device is clean --- [/dev/sdai] - Device is clean --- [/dev/sdaj] - Device is clean --- [/dev/sdak] - Device is clean --- [/dev/sdb] - Device is clean --- [/dev/sdc] - Device is clean --- [/dev/sdd] - Device is clean --- [/dev/sde] - Device is clean --- [/dev/sdf] - Device is clean --- [/dev/sdg] - Device is clean --- [/dev/sdh] - Device is clean --- [/dev/sdi] - Device is clean --- [/dev/sdj] - Device is clean --- [/dev/sdk] - Device is clean --- [/dev/sdl] - Device is clean --- [/dev/sdm] - Device is clean --- [/dev/sdn] - Device is clean --- [/dev/sdo] - Device is clean --- [/dev/sdp] - Device is clean --- [/dev/sdq] - Device is clean --- [/dev/sdr] - Device is clean --- [/dev/sds] - Device is clean --- [/dev/sdt] - Device is clean --- [/dev/sdu] - Device is clean --- [/dev/sdv] - Device is clean --- [/dev/sdw] - Device is clean --- [/dev/sdx] - Device is clean --- [/dev/sdy] - Device is clean --- [/dev/sdz] - Device is clean|

**Comment by Napsty** [comment]
Fixed with commit 0a0a3f81a7b15df13ee939af529d7c110b22467b . Thanks for your help!
