### ISSUE TITLE
add aacraid

### ISSUE THREAD

**Issue by antonzhelyazkov** [Napsty/check_smart#63]
Hi, can you add support for SAS disks on adaptec raids?

here is smartctl command line
smartctl -a /dev/sda -d aacraid,0,0,1

**Comment by Napsty** [comment]
@antonzhelyazkov Does this version work? 
https://raw.githubusercontent.com/Napsty/check_smart/784804c657d1a060f1b72121eca3050cced5d3e1/check_smart.pl

**Comment by antonzhelyazkov** [comment]
Yes, it seems working. I've installed it on one server.
Next week I will update all servers with adaptec controllers. I'll let you know if an error occurs.

**Comment by Napsty** [comment]
Fixed in #69
