### ISSUE TITLE
Feature request: An exclude-flag when using -g option

### ISSUE THREAD

**Issue by jonasalexandersson** [Napsty/check_smart#7]
It would be wonderful if it was possible to use the g-option with an optional exclude-flag.
Right now I have multiple harddrives on one of my systems, and also a 3g-modem connected.
The 3g-modem has a usb-hdd (dev/sdd), and when I'm using the g-option, the overall health becomes:
UNKNOWN: [/dev/sda] - Device is clean ... [/dev/sdd] - No health status line found ---

As said, it would be nice if one could do the following:
/usr/lib/nagios/plugins/check_smart.pl -i ata -g /dev/sd --exlude /dev/sdd /dev/sde

**Comment by Napsty** [comment]
Hi @jonasalexandersson 
Did you see https://github.com/Napsty/check_smart/issues/13 ? Does this solve your request?
